### PR TITLE
Add project management

### PR DESCRIPTION
**Pull request by hectorsector**
This PR adds project tracking to the course.

Still in progress until I add a project board and cards in the `before:` step.

### CODE REVIEW

**Comment by hectorsector** [comment]
Still working on this, @a-a-ron. I'm troubleshooting what seems to be disparity between Octokit and the GitHub API. 

In the GitHub API, the endpoint to [Create a project card](https://developer.github.com/v3/projects/cards/#create-a-project-card) doesn't require a `column_id`, but in Octokit, [the same endpoint](https://octokit.github.io/rest.js/#octokit-routes-projects-create-card) does -- however when I do try to include the column_id in which I want the project card I get this:

```shell
12:14:31.919Z ERROR probot: Error in working-in-large-repositories:before:octokit[15] (course_id=95, course_repo=217290285, course_slug=working-in-large-repositories, user=hectorsector, registration_id=145, step_id=before, action_id=15, action_type=octokit)
  HttpError: {"message":"Validation Failed","errors":[{"resource":"ProjectCard","code":"unprocessable","field":"data","message":"Could not resolve to a node with the global id of 'MDExOnB1bGxSZXF1ZXN0MzMyMDE1MTM5'."}],"documentation_url":"https://developer.github.com/v3/projects/cards/#create-a-project-card"}
      at response.text.then.message (/Users/hec/github/learning-lab/node_modules/@octokit/rest/lib/request/request.js:72:19)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

/cc @JasonEtco in case you know what's going on here.

**Comment by hectorsector** [comment]
An update on this: I'm not so worried about needing a `column_id`, I think this is required because the GitHub API endpoint is `/projects/columns/:column_id/cards` so the `column_id` is required to access that.

However, I think there's something funky about what Learning Lab is using to make the Octokit request. I've confirmed that the structure of the API response includes the `id` field which I need:

```json
{
  "data":{
    "url":"https://api.github.com/projects/columns/6911243",
    "project_url":"https://api.github.com/projects/3415098",
    "cards_url":"https://api.github.com/projects/columns/6911243/cards",
    "id":6911243,
    "node_id":"MDEzOlByb2plY3RDb2x1bW42OTExMjQz",
    "name":"Done",
    "created_at":"2019-10-24T14:58:18Z","updated_at":
    "2019-10-24T14:58:18Z"
  }, ...
```

**However**, for some reason when I call `project_id: '%actions.projectBoard.data.id%'`, it actually sends through `node_id`, hence the error message.

**Comment by hectorsector** [comment]
The issue with the octokit call is now [resolved](https://github.com/githubtraining/working-in-large-repositories/pull/8/commits/e2b96690e2d5f825c7c0d98945d0a8f761c55e60)! User error, ftw.

Turning my attention to making sure the project step makes sense in the flow of the course.

**Comment by a-a-ron** [comment]
Thanks @hectorsector !!

**Comment by hectorsector** [comment]
@a-a-ron merging this now that it has a proper Project step so that we get a deployment we can work with. 

I will keep working on this course to improve the responses and tell a cohesive story, but this is a good time to 👀 and make sure that it makes sense and aligns with what you wanted.

**Pull request merged**
